export const CHANGE_TASK_POSITION = "CHANGE_TASK_POSITION";
export const CHANGE_TASK_BOARD = "CHANGE_TASK_BOARD";
export const CHANGE_BOARD_POSITION = "CHANGE_BOARD_POSITION";
export const CHANGE_BOARD_TITLE = "CHANGE_BOARD_TITLE";
export const CHANGE_TASK_TITLE = "CHANGE_TASK_TITLE";
